sistrack/inspections/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^devices/$', views.DeviceListView.as_view(), name='devices'),
    url(r'^device/(?P<pk>\d+)$', views.DeviceDetailView.as_view(), name='device-detail'),
]

urlpatterns += [
    url(r'^mytests/$', views.DeviceTestedByUserListView.as_view(), name='my-tests'),
]

urlpatterns += [
    url(r'^alltests/$', views.AllDevicesTestedListView.as_view(), name='all-tests'),
]

sistrack/sistrack/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^inspections/', include('inspections.urls')),
]

urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/inspections/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistrack/inspections/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid # Required for unique test instances

# Create your models here.

class Document(models.Model):
    doc_unit = models.ForeignKey('Location', on_delete=models.SET_NULL, blank=True, null=True)
    doc_number = models.CharField(max_length=50)
    doc_name = models.CharField(max_length=50)

    DOC_TYPE = (
        ('c','Cause and Effect'),
        ('d','Data Sheet'),
        ('p','P&ID'),
        ('o','other'),
    )

    doc_type = models.CharField(max_length=50, choices=DOC_TYPE, blank=True, default='o')

    class Meta:
        ordering = ["doc_number"]

    def __str__(self):
        return '{0}-{1}'.format(self.doc_number,self.doc_type)


class Location(models.Model):
    facility = models.CharField(max_length=50)
    plant = models.CharField(max_length=50)
    area = models.CharField(max_length=50)
    unit = models.CharField(max_length=50)
    description = models.CharField(max_length=50)

    class Meta:
        ordering = ["unit"]

    def __str__(self):
        return '{0}'.format('Unit ' + self.unit)


class DeviceType(models.Model):
    name = models.CharField(max_length=50)
    CATEGORY = (
        ('i','Input Element'),
        ('o','Output Element'),
    )
    category = models.CharField(max_length=1, choices=CATEGORY)

    class Meta:
        ordering = ["category"]

    def __str__(self):
        return '{0}-({1})'.format(self.name,self.category)


class Device(models.Model):
    tagnumber = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    devicetype = models.ForeignKey(DeviceType, on_delete=models.SET_NULL, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["tagnumber"]

    def __str__(self):
        return self.tagnumber

    def get_absolute_url(self):
        return reverse('device-detail', args=[str(self.id)])


class TestInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular device test")
    device = models.ForeignKey(Device, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    test_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    inspector = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_date and date.today() > self.due_date:
            return True
        return False

    TEST_STATUS = (
    ('o', 'Overdue'),
    ('s', 'Scheduled'),
    )

    TEST_RESULT = (
    ('p', 'Passed'),
    ('f', 'Failed'),
    )

    status = models.CharField(max_length=1, choices=TEST_STATUS, blank=True, default='s')
    result = models.CharField(max_length=1, choices=TEST_RESULT, blank=True)
    comments = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ["due_date"]
        permissions = (("can_mark_approved", "Mark test as approved"),)

    def __str__(self):
        return '%s (%s)' % (self.id,self.device.tagnumber)


class Interlock(models.Model):
    interlock_unit = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    interlock_number = models.CharField(max_length=50)
    interlock_description = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        ordering = ["interlock_number"]

    def __str__(self):
        return '{0}'.format(self.interlock_number)


class Ipl(models.Model):
    ipl_unit = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    initiator = models.CharField(max_length=50)
    ipl_description = models.CharField(max_length=300)
    ipl_narrative = models.TextField(blank=True)
    ipl_interlock_number = models.ForeignKey(Interlock, on_delete=models.SET_NULL, blank=True, null=True)
    ipl_doc_references = models.ManyToManyField(Document, blank=True, verbose_name="IPL reference documents")
    input_elements = models.ManyToManyField(Device, blank=True, related_name='+', related_query_name="IPL input elements")
    output_elements = models.ManyToManyField(Device, blank=True, related_name='+', related_query_name="IPL output elements")

    class Meta:
        ordering = ["ipl_unit"]

    def __str__(self):
        return '{0}-{1}'.format(self.initiator,self.ipl_description)

sistrack/inspections/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Location, Device, DeviceType, TestInstance, Document, Interlock, Ipl
# Create your views here.

def index(request):
    devcount = Device.objects.all().count()
    ipl_count = Ipl.objects.all().count()
    interlock_count = Interlock.objects.all().count()
    doc_count = Document.objects.all().count()
    location_count = Location.objects.all().count()
    failedcount = TestInstance.objects.filter(result='f').count()
    test_count = TestInstance.objects.filter(test_date__year=2017).count()
    testedthismonth = TestInstance.objects.all().count()
    testedthisyear = TestInstance.objects.filter(test_date__year=2017).count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    return render(request, 'index.html', {'devcount':devcount, 'failedcount':failedcount, 'testedthismonth':testedthismonth, 'testedthisyear':testedthisyear, 'num_visits':num_visits, 'ipl_count':ipl_count, 'interlock_count':interlock_count, 'doc_count':doc_count, 'location_count':location_count, 'test_count':test_count})

class DeviceListView(generic.ListView):
    model = Device
    paginate_by = 10

class DeviceDetailView(generic.DetailView):
    model = Device

class DeviceTestedByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing devices tested by current user.
    """
    model = TestInstance
    template_name ='inspections/testinstance_list_tested_user.html'
    paginate_by = 10

    def get_queryset(self):
        return TestInstance.objects.filter(inspector=self.request.user).filter(status__exact='s').order_by('due_date')

class AllDevicesTestedListView(PermissionRequiredMixin,generic.ListView):
    """
    Generic class-based view listing all devices tested.
    """
    permission_required = 'inspections.can_mark_approved'
    model = TestInstance
    template_name ='inspections/all_devices_tested.html'
    paginate_by = 10

    def get_queryset(self):
        return TestInstance.objects.filter(status__exact='s').order_by('due_date')

sistrack/inspections/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    {% block title %}<title>SisTrack</title>{% endblock %}
  </head>
  <body>
    <div class="container-fluid">
    <!-- Content here -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">SisTrack</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'devices' %}">Device List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if user.is_authenticated %}{{ user.get_username }}{% else %}Hello Guest
            {% endif %}
            </button>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'my-tests' %}"> My Tests</a>
              {% if perms.inspections.can_mark_approved %}
              <a class="dropdown-item" href="{% url 'all-tests' %}"> All Tests</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Login</a>
              <a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Register</a>
             {% endif %}
             </div>
          </div>
        </div>
      </nav>

      <div class="col mt-2">
        <h1>Sistrack</h1> Ensure safety devices are in place!<hr>
      </div>

      <div class="row">

        <div class="col-2">
          {% block sidebar %}<div class="alert alert-secondary" role="alert" style="min-height:600px;">
          <p>side navigation</p>
          </div>{% endblock %}
        </div>

        <div class="col-10">

        {% block content %}{% endblock %}

        {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
          {% endblock %}
        </div>


      </div>

      <div class="row">
        <div class="col">
          <div class="alert alert-primary" role="alert" style="min-height:200px;">
          <p>This is our footer</p>
          </div>
        </div>
      </div>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

sistrack/inspections/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col-4">
      <div class="alert alert-primary" role="alert" style="min-height:200px;">
        <h4><strong>{{ interlock_count }}</strong>  Interlocks</h4>
      </div>
    </div>
    <div class="col-4">
      <div class="alert alert-secondary" role="alert" style="min-height:200px;">
        <h4><strong>{{ location_count }}</strong>  Locations</h4>
      </div>
    </div>
    <div class="col-4">
      <div class="alert alert-success" role="alert" style="min-height:200px;">
        <h4><strong>{{ test_count }}</strong>  Inspection records</h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-4">
      <div class="alert alert-primary" role="alert" style="min-height:200px;">
        <h4><strong>{{ devcount }}</strong>  Safety devices</h4>
      </div>
    </div>
    <div class="col-4">
      <div class="alert alert-secondary" role="alert" style="min-height:200px;">
        <h4><strong>{{ ipl_count }}</strong>  IPL's</h4>
      </div>
    </div>
    <div class="col-4">
      <div class="alert alert-success" role="alert" style="min-height:200px;">
        <h4><strong>{{ doc_count }}</strong>  PSI Documents</h4>
      </div>
      <br>
    </div><hr>
  </div>
  <div class="alert alert-dark" role="alert">
    <p>Devices tested this month = <strong>{{ testedthismonth }}</strong></p>
    <p>Devices tested this year = <strong>{{ testedthisyear }}</strong></p>
    <p>Number of failed tests = <strong>{{ failedcount }}</strong></p>
  </div>
</div>

<p>You have visited this page {{ num_visits }} {% if num_visits == 1 %} time {% else %} times {% endif %}</p>
{% endblock %}

sistrack/inspections/templates/inspections/all_devices_tested.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Devices Tested</h1>

    {% if testinstance_list %}
    <ul>

      {% for testinst in testinstance_list %}
      <li class="{% if testinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'device-detail' testinst.device.pk %}">{{testinst.device.tagnumber}}</a> ({{ testinst.test_date }}) -  {{ testinst.inspector.last_name}}, {{ testinst.inspector.first_name}}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no devices tested.</p>
    {% endif %}
{% endblock %}

sistrack/inspections/templates/inspections/device_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h2>{{ device.tagnumber }}</h2>
<p>{{ device.description }}</p>
<hr>

<p>Area: {{ device.location.area }} / Unit: {{ device.location }}</p>
<p>Device type: {{ device.devicetype }}</p><br>

<h3>Device Test History</h3>
<hr>
{% if device.testinstance_set.all %}


{% for device in device.testinstance_set.all %}
{{ device.test_date }}<p>Tested by: <strong>{{ device.inspector.last_name }}, {{ device.inspector.first_name }}</strong> ({{ device.get_result_display }})</p><hr>

{% endfor %}

{% else %}
<p>No test records found</p>
{% endif %}
{% endblock %}

sistrack/inspections/templates/inspections/device_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>SIS Device List</h1>
{% if device_list %}
<ul>

{% for device in device_list %}

<li><a href="{{ device.get_absolute_url }}">{{ device.tagnumber }}</a>  - {{ device.description }}</li>

{% endfor %}

</ul>
{% else %}
<p>no devices</p>
{% endif %}
{% endblock %}

sistrack/inspections/templates/inspections/testinstance_list_tested_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Tested Devices</h1>

    {% if testinstance_list %}
    <ul>

      {% for testinst in testinstance_list %}
      <li class="{% if testinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'device-detail' testinst.device.pk %}">{{testinst.device.tagnumber}}</a> ({{ testinst.due_date }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no devices tested.</p>
    {% endif %}
{% endblock %}